#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.15
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Rison
  class ArrayParser < Racc::Parser

module_eval(<<'...end array_parser.y/module_eval...', 'array_parser.y', 72)

attr_reader :source, :input

def initialize(source)
  @source = source
  @input = StringScanner.new(source)
end

def self.parse(source)
  self.new(source).do_parse
rescue Racc::ParseError => exn
  raise ParserError.new("#{exn.message} in #{source}")
end

def next_token
  case
  when input.eos?
    [false, false]
  when input.scan(/'/)
    [:QUOTE, nil]
  when input.scan(/\(/)
    [:LPAREN, nil]
  when input.scan(/\)/)
    [:RPAREN, nil]
  when input.scan(/:/)
    [:COLON, input.matched]
  when input.scan(/\./)
    [:DOT, input.matched]
  when input.scan(/\,/)
    [:COMMA, input.matched]
  when input.scan(/!/)
    [:EXCLAM, input.matched]
  when input.scan(/\-/)
    [:MINUS, input.matched]
  when input.scan(/e/)
    [:E, input.matched]
  when input.scan(/t/)
    [:T, input.matched]
  when input.scan(/f/)
    [:F, input.matched]
  when input.scan(/n/)
    [:N, input.matched]
  # Originally, 0 is not allowed at the beginning of the number, but rison.js accepts this.
  when input.scan(/[0-9]/)
    [:DIGIT, input.matched]
  # IDSTART and IDCHAR should originally accept only the ASCII symbols `-_./~`, but rison.js accepts other symbols.
  # @see https://rison.io/
  # @see https://github.com/Nanonid/rison/blob/e64af6c096fd30950ec32cfd48526ca6ee21649d/js/rison.js#L77-L84
  when input.scan(/[^\-0-9 '!:\(\),\*@¥\$]/)
    [:IDSTART, input.matched]
  when input.scan(/[^ '!:\(\),\*@¥\$]/)
    [:IDCHAR, input.matched]
  when input.scan(/[^\'\!]/)
    [:STRCHAR, input.matched]
  end
end
...end array_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    65,    53,    51,    73,    55,    34,    17,    18,    19,    26,
    28,    29,    15,    16,    20,    32,    25,    55,    78,    24,
    46,    34,    17,    18,    19,    26,    28,    29,    15,    16,
    20,    32,    41,     4,    55,    56,    61,     5,    17,    18,
    19,    60,    23,    22,    15,    16,    20,     2,     4,    57,
   -38,    58,     5,    17,    18,    19,    62,    23,    22,    15,
    16,    20,    41,     4,    66,    63,    64,     5,    17,    18,
    19,    53,    23,    22,    15,    16,    20,    41,    55,    35,
    41,    55,   nil,    17,    18,    19,    17,    18,    19,    15,
    16,    20,    15,    16,    20,    41,     4,   nil,   nil,   nil,
     5,    17,    18,    19,   nil,    23,    22,    15,    16,    20,
    34,    17,    18,    19,    26,    28,    29,    15,    16,    20,
    32,    17,    18,    19,    26,    28,    29,    15,    16,    20,
    17,    18,    19,    26,    28,    29,    15,    16,    20,    42,
   nil,   nil,   nil,   nil,    43,    44,    45 ]

racc_action_check = [
    41,    21,    21,    53,    55,    41,    41,    41,    41,    41,
    41,    41,    41,    41,    41,    41,     2,    56,    67,     1,
     6,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    46,    46,    22,    23,    34,    46,    46,    46,
    46,    34,    46,    46,    46,    46,    46,     0,     0,    24,
    25,    30,     0,     0,     0,     0,    36,     0,     0,     0,
     0,     0,    42,    42,    42,    37,    38,    42,    42,    42,
    42,    49,    42,    42,    42,    42,    42,     4,    51,     4,
    63,    52,   nil,     4,     4,     4,    63,    63,    63,     4,
     4,     4,    63,    63,    63,    64,    64,   nil,   nil,   nil,
    64,    64,    64,    64,   nil,    64,    64,    64,    64,    64,
    31,    31,    31,    31,    31,    31,    31,    31,    31,    31,
    31,    48,    48,    48,    48,    48,    48,    48,    48,    48,
    14,    14,    14,    14,    14,    14,    14,    14,    14,     5,
   nil,   nil,   nil,   nil,     5,     5,     5 ]

racc_action_pointer = [
    45,    19,    14,   nil,    75,   136,    15,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   122,   nil,   nil,   nil,   nil,   nil,
   nil,   -14,    21,    22,    49,    45,   nil,   nil,   nil,   nil,
    49,   103,   nil,   nil,    34,   nil,    52,    60,    60,   nil,
   nil,    -2,    60,   nil,   nil,   nil,    30,   nil,   113,    56,
   nil,    65,    68,    -9,   nil,    -9,     4,   nil,   nil,   nil,
   nil,   nil,   nil,    78,    93,   nil,   nil,    14,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -60,   -60,   -60,    -2,   -60,   -60,   -10,   -14,   -15,   -16,
   -17,   -18,   -19,   -20,   -24,   -32,   -33,   -34,   -35,   -36,
   -37,   -46,   -50,   -60,   -60,    -1,   -28,   -29,   -30,   -31,
   -60,   -40,   -42,   -43,   -60,    -3,   -60,    -5,   -60,   -12,
   -13,   -60,   -60,   -21,   -22,   -23,   -60,   -25,   -26,   -47,
   -48,   -60,   -60,   -58,   -51,   -56,   -52,    79,   -39,   -41,
   -44,   -45,    -4,   -60,   -60,   -38,    -8,   -60,   -11,   -27,
   -49,   -54,   -55,   -59,   -57,   -53,    -6,    -7,    -9 ]

racc_goto_table = [
    40,    36,    39,     3,    27,    54,    47,    48,    50,     1,
    59,    49,    77,   nil,   nil,   nil,    27,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    27,    71,    72,    70,   nil,    74,    75,
    69,    48,   nil,    27,   nil,    67,   nil,   nil,   nil,    68,
    27,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    40,
    76,    39 ]

racc_goto_check = [
    10,     4,     9,     2,    14,    22,    15,    16,    21,     1,
    17,    20,     7,   nil,   nil,   nil,    14,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    14,    22,    22,    21,   nil,    22,    22,
    15,    16,   nil,    14,   nil,     2,   nil,   nil,   nil,     2,
    14,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    10,
     4,     9 ]

racc_goto_pointer = [
   nil,     9,     3,   nil,    -3,   nil,   nil,   -52,   nil,    -2,
    -4,   nil,   nil,   nil,     2,    -8,    -7,   -21,   nil,   nil,
   -10,   -13,   -17,   nil ]

racc_goto_default = [
   nil,   nil,   nil,    10,   nil,    37,    38,     6,    11,     7,
     8,     9,    12,    13,    14,   nil,    33,    30,    31,    21,
   nil,   nil,   nil,    52 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 19, :_reduce_1,
  1, 19, :_reduce_none,
  2, 21, :_reduce_3,
  3, 21, :_reduce_4,
  1, 22, :_reduce_none,
  3, 22, :_reduce_6,
  3, 23, :_reduce_7,
  3, 26, :_reduce_8,
  4, 26, :_reduce_9,
  1, 20, :_reduce_10,
  3, 20, :_reduce_11,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  2, 30, :_reduce_21,
  2, 30, :_reduce_22,
  2, 31, :_reduce_23,
  1, 27, :_reduce_none,
  2, 27, :_reduce_25,
  1, 33, :_reduce_none,
  2, 33, :_reduce_27,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  2, 28, :_reduce_38,
  3, 28, :_reduce_39,
  1, 35, :_reduce_none,
  2, 35, :_reduce_41,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  2, 36, :_reduce_44,
  2, 36, :_reduce_45,
  1, 29, :_reduce_46,
  2, 29, :_reduce_47,
  2, 29, :_reduce_48,
  3, 29, :_reduce_49,
  1, 37, :_reduce_50,
  2, 37, :_reduce_51,
  2, 37, :_reduce_52,
  3, 37, :_reduce_53,
  2, 38, :_reduce_54,
  2, 39, :_reduce_55,
  1, 40, :_reduce_none,
  2, 40, :_reduce_57,
  1, 41, :_reduce_58,
  2, 41, :_reduce_59 ]

racc_reduce_n = 60

racc_shift_n = 79

racc_token_table = {
  false => 0,
  :error => 1,
  :QUOTE => 2,
  :LPAREN => 3,
  :RPAREN => 4,
  :COMMA => 5,
  :COLON => 6,
  :EXCLAM => 7,
  :T => 8,
  :F => 9,
  :N => 10,
  :IDCHAR => 11,
  :MINUS => 12,
  :DIGIT => 13,
  :IDSTART => 14,
  :E => 15,
  :DOT => 16,
  :STRCHAR => 17 }

racc_nt_base = 18

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "QUOTE",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "COLON",
  "EXCLAM",
  "T",
  "F",
  "N",
  "IDCHAR",
  "MINUS",
  "DIGIT",
  "IDSTART",
  "E",
  "DOT",
  "STRCHAR",
  "$start",
  "target",
  "elements",
  "object",
  "members",
  "pair",
  "key",
  "value",
  "array",
  "id",
  "string",
  "number",
  "bool",
  "null",
  "idstart",
  "idchars",
  "idchar",
  "strchars",
  "strchar",
  "int",
  "frac",
  "exp",
  "digits",
  "e" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'array_parser.y', 3)
  def _reduce_1(val, _values, result)
     result = [] 
    result
  end
.,.,

# reduce 2 omitted

module_eval(<<'.,.,', 'array_parser.y', 6)
  def _reduce_3(val, _values, result)
     result = {} 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 7)
  def _reduce_4(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 5 omitted

module_eval(<<'.,.,', 'array_parser.y', 10)
  def _reduce_6(val, _values, result)
     result = val[0].merge(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 12)
  def _reduce_7(val, _values, result)
     result = { val[0] => val[2] } 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 14)
  def _reduce_8(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 15)
  def _reduce_9(val, _values, result)
     result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 17)
  def _reduce_10(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 18)
  def _reduce_11(val, _values, result)
     result = val[2].unshift(val[0]) 
    result
  end
.,.,

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

module_eval(<<'.,.,', 'array_parser.y', 24)
  def _reduce_21(val, _values, result)
     result = true 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 25)
  def _reduce_22(val, _values, result)
     result = false 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 27)
  def _reduce_23(val, _values, result)
     result = nil 
    result
  end
.,.,

# reduce 24 omitted

module_eval(<<'.,.,', 'array_parser.y', 30)
  def _reduce_25(val, _values, result)
     result = val[0] + val[1] 
    result
  end
.,.,

# reduce 26 omitted

module_eval(<<'.,.,', 'array_parser.y', 33)
  def _reduce_27(val, _values, result)
     result = val[0] + val[1] 
    result
  end
.,.,

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

module_eval(<<'.,.,', 'array_parser.y', 39)
  def _reduce_38(val, _values, result)
     result = '' 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 40)
  def _reduce_39(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 40 omitted

module_eval(<<'.,.,', 'array_parser.y', 43)
  def _reduce_41(val, _values, result)
     result = val[0] + val[1] 
    result
  end
.,.,

# reduce 42 omitted

# reduce 43 omitted

module_eval(<<'.,.,', 'array_parser.y', 47)
  def _reduce_44(val, _values, result)
     result = '!' 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 48)
  def _reduce_45(val, _values, result)
     result = "'" 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 50)
  def _reduce_46(val, _values, result)
     result = val[0].to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 51)
  def _reduce_47(val, _values, result)
     result = "#{val[0]}#{val[1]}".to_f 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 52)
  def _reduce_48(val, _values, result)
     result = "#{val[0]}#{val[1]}".to_f 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 53)
  def _reduce_49(val, _values, result)
     result = "#{val[0]}#{val[1]}#{val[2]}".to_f 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 55)
  def _reduce_50(val, _values, result)
     result = val[0].to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 56)
  def _reduce_51(val, _values, result)
     result = "#{val[0]}#{val[1]}".to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 57)
  def _reduce_52(val, _values, result)
     result = "-#{val[1]}".to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 58)
  def _reduce_53(val, _values, result)
     result = "-#{val[1]}#{val[2]}".to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 60)
  def _reduce_54(val, _values, result)
     result = "#{val[0]}#{val[1]}" 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 62)
  def _reduce_55(val, _values, result)
     result = "#{val[0]}#{val[1]}" 
    result
  end
.,.,

# reduce 56 omitted

module_eval(<<'.,.,', 'array_parser.y', 65)
  def _reduce_57(val, _values, result)
     result = "#{val[0]}#{val[1]}" 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 67)
  def _reduce_58(val, _values, result)
     result = 'e' 
    result
  end
.,.,

module_eval(<<'.,.,', 'array_parser.y', 68)
  def _reduce_59(val, _values, result)
     result = "e-" 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class ArrayParser
  end   # module Rison
