#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.15
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Rison
  module Object
    class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 76)

attr_reader :source, :input

def initialize(source)
  @source = source
  @input = StringScanner.new(source)
end

def self.parse(source)
  self.new(source).do_parse
rescue Racc::ParseError => exn
  raise ParserError.new("#{exn.message} in #{source}")
end

def next_token
  case
  when input.eos?
    [false, false]
  when input.scan(/'/)
    [:QUOTE, input.matched]
  when input.scan(/\(/)
    [:LPAREN, input.matched]
  when input.scan(/\)/)
    [:RPAREN, input.matched]
  when input.scan(/:/)
    [:COLON, input.matched]
  when input.scan(/\./)
    [:DOT, input.matched]
  when input.scan(/\,/)
    [:COMMA, input.matched]
  when input.scan(/!/)
    [:EXCLAM, input.matched]
  when input.scan(/\-/)
    [:MINUS, input.matched]
  when input.scan(/e/)
    [:E, input.matched]
  when input.scan(/t/)
    [:T, input.matched]
  when input.scan(/f/)
    [:F, input.matched]
  when input.scan(/n/)
    [:N, input.matched]
  # Originally, 0 is not allowed at the beginning of the number, but rison.js accepts this.
  when input.scan(/[0-9]/)
    [:DIGIT, input.matched]
  # IDSTART and IDCHAR should originally accept only the ASCII symbols `-_./~`, but rison.js accepts other symbols.
  # @see https://rison.io/
  # @see https://github.com/Nanonid/rison/blob/e64af6c096fd30950ec32cfd48526ca6ee21649d/js/rison.js#L77-L84
  when input.scan(/[^\-0-9 '!:\(\),\*@\$]/)
    [:IDSTART, input.matched]
  when input.scan(/[^ '!:\(\),\*@\$]/)
    [:IDCHAR, input.matched]
  when input.scan(/[^\'\!]/)
    [:STRCHAR, input.matched]
  end
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    16,    27,    28,    29,    26,    25,    11,    12,    13,    17,
    19,    20,     9,    10,    14,    23,    55,    27,    28,    29,
    26,    25,    11,    12,    13,    17,    19,    20,     9,    10,
    14,    23,    40,    41,    66,    64,    38,    43,    11,    12,
    13,    37,    53,    52,     9,    10,    14,    27,    28,    29,
    26,    25,    11,    12,    13,    17,    19,    20,     9,    10,
    14,    23,    40,    68,    69,    70,    81,    66,    11,    12,
    13,    68,    40,    41,     9,    10,    14,    43,    11,    12,
    13,    68,    53,    52,     9,    10,    14,    40,    30,    56,
    31,    58,    34,    11,    12,    13,    59,    60,    61,     9,
    10,    14,    40,    41,    71,   -38,    77,    43,    11,    12,
    13,     2,    53,    52,     9,    10,    14,    11,    12,    13,
    35,    68,    68,     9,    10,    14,    11,    12,    13,    17,
    19,    20,     9,    10,    14,    11,    12,    13,    17,    19,
    20,     9,    10,    14,    15,    80 ]

racc_action_check = [
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    40,    40,    40,    40,
    40,    40,    40,    40,    40,    40,    40,    40,    40,    40,
    40,    40,    81,    81,    51,    51,    25,    81,    81,    81,
    81,    25,    81,    81,    81,    81,    81,    22,    22,    22,
    22,    22,    22,    22,    22,    22,    22,    22,    22,    22,
    22,    22,    30,    52,    53,    57,    73,    62,    30,    30,
    30,    64,    31,    31,    30,    30,    30,    31,    31,    31,
    31,    65,    31,    31,    31,    31,    31,    41,     4,    41,
     5,    43,    15,    41,    41,    41,    43,    43,    43,    41,
    41,    41,    58,    58,    58,    16,    66,    58,    58,    58,
    58,     0,    58,    58,    58,    58,    58,     0,     0,     0,
    21,    68,    69,     0,     0,     0,     8,     8,     8,     8,
     8,     8,     8,     8,     8,    33,    33,    33,    33,    33,
    33,    33,    33,    33,     1,    72 ]

racc_action_pointer = [
   109,   144,    -2,   nil,    83,    84,   nil,   nil,   118,   nil,
   nil,   nil,   nil,   nil,   nil,    92,    99,   nil,   nil,   nil,
   nil,   118,    44,   nil,   nil,    34,   nil,   nil,   nil,   nil,
    60,    70,   nil,   127,   nil,   nil,   nil,   nil,   nil,   nil,
    14,    85,   nil,    88,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    19,    50,    51,   nil,   nil,   nil,    61,   100,   nil,
   nil,   nil,    52,   nil,    58,    68,    94,   nil,   108,   109,
   nil,   nil,   141,    61,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    30,   nil ]

racc_action_default = [
   -64,   -64,   -64,    -2,    -5,   -64,   -12,   -13,   -24,   -32,
   -33,   -34,   -35,   -36,   -37,   -64,    -1,   -28,   -29,   -30,
   -31,   -64,   -40,   -42,   -43,   -64,   -46,   -47,   -48,   -49,
   -64,   -64,   -25,   -26,    83,   -39,   -41,   -44,   -45,    -6,
   -64,   -64,    -7,   -64,   -14,   -15,   -16,   -17,   -18,   -19,
   -20,   -50,   -54,   -64,   -27,   -38,    -3,   -64,   -64,   -21,
   -22,   -23,   -51,   -52,   -64,   -64,   -62,   -55,   -60,   -56,
    -4,    -8,   -64,   -10,   -53,   -58,   -59,   -63,   -61,   -57,
    -9,   -64,   -11 ]

racc_goto_table = [
    44,    45,     3,    18,    32,    33,    63,    42,    72,    18,
    36,    62,     1,   nil,   nil,   nil,   nil,    74,   nil,   nil,
   nil,   nil,   nil,    18,   nil,   nil,   nil,    44,    45,    54,
    33,    82,    39,   nil,    18,   nil,    67,   nil,   nil,   nil,
   nil,    18,   nil,    57,   nil,   nil,   nil,   nil,    75,    76,
    44,    45,    78,    79 ]

racc_goto_check = [
     9,    10,     2,    14,    15,    16,    21,     6,     8,    14,
    17,    20,     1,   nil,   nil,   nil,   nil,    21,   nil,   nil,
   nil,   nil,   nil,    14,   nil,   nil,   nil,     9,    10,    15,
    16,     8,     2,   nil,    14,   nil,    22,   nil,   nil,   nil,
   nil,    14,   nil,     2,   nil,   nil,   nil,   nil,    22,    22,
     9,    10,    22,    22 ]

racc_goto_pointer = [
   nil,    12,     2,   nil,   nil,   nil,   -24,   nil,   -50,   -31,
   -30,   nil,   nil,   nil,     1,    -4,    -3,   -12,   nil,   nil,
   -40,   -45,   -16,   nil ]

racc_goto_default = [
   nil,   nil,   nil,    47,     4,     5,    73,    48,   nil,     6,
     7,    46,    49,    50,     8,   nil,    24,    21,    22,    51,
   nil,   nil,   nil,    65 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 19, :_reduce_1,
  1, 19, :_reduce_none,
  2, 21, :_reduce_3,
  3, 21, :_reduce_4,
  1, 20, :_reduce_none,
  3, 20, :_reduce_6,
  3, 22, :_reduce_7,
  3, 25, :_reduce_8,
  4, 25, :_reduce_9,
  1, 26, :_reduce_10,
  3, 26, :_reduce_11,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  2, 30, :_reduce_21,
  2, 30, :_reduce_22,
  2, 31, :_reduce_23,
  1, 27, :_reduce_none,
  2, 27, :_reduce_25,
  1, 33, :_reduce_none,
  2, 33, :_reduce_27,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  2, 28, :_reduce_38,
  3, 28, :_reduce_39,
  1, 35, :_reduce_none,
  2, 35, :_reduce_41,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  2, 36, :_reduce_44,
  2, 36, :_reduce_45,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 29, :_reduce_50,
  2, 29, :_reduce_51,
  2, 29, :_reduce_52,
  3, 29, :_reduce_53,
  1, 37, :_reduce_54,
  2, 37, :_reduce_55,
  2, 37, :_reduce_56,
  3, 37, :_reduce_57,
  2, 38, :_reduce_58,
  2, 39, :_reduce_59,
  1, 40, :_reduce_none,
  2, 40, :_reduce_61,
  1, 41, :_reduce_62,
  2, 41, :_reduce_63 ]

racc_reduce_n = 64

racc_shift_n = 83

racc_token_table = {
  false => 0,
  :error => 1,
  :QUOTE => 2,
  :LPAREN => 3,
  :RPAREN => 4,
  :COMMA => 5,
  :COLON => 6,
  :EXCLAM => 7,
  :T => 8,
  :F => 9,
  :N => 10,
  :IDCHAR => 11,
  :MINUS => 12,
  :DIGIT => 13,
  :IDSTART => 14,
  :E => 15,
  :DOT => 16,
  :STRCHAR => 17 }

racc_nt_base = 18

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "QUOTE",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "COLON",
  "EXCLAM",
  "T",
  "F",
  "N",
  "IDCHAR",
  "MINUS",
  "DIGIT",
  "IDSTART",
  "E",
  "DOT",
  "STRCHAR",
  "$start",
  "target",
  "members",
  "object",
  "pair",
  "key",
  "value",
  "array",
  "elements",
  "id",
  "string",
  "number",
  "bool",
  "null",
  "idstart",
  "idchars",
  "idchar",
  "strchars",
  "strchar",
  "int",
  "frac",
  "exp",
  "digits",
  "e" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 3)
  def _reduce_1(val, _values, result)
     result = {} 
    result
  end
.,.,

# reduce 2 omitted

module_eval(<<'.,.,', 'parser.y', 6)
  def _reduce_3(val, _values, result)
     result = {} 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 7)
  def _reduce_4(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 5 omitted

module_eval(<<'.,.,', 'parser.y', 10)
  def _reduce_6(val, _values, result)
     result = val[0].merge(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 12)
  def _reduce_7(val, _values, result)
     result = { val[0] => val[2] } 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 14)
  def _reduce_8(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 15)
  def _reduce_9(val, _values, result)
     result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_10(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_11(val, _values, result)
     result = val[2].unshift(val[0]) 
    result
  end
.,.,

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_21(val, _values, result)
     result = true 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_22(val, _values, result)
     result = false 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_23(val, _values, result)
     result = nil 
    result
  end
.,.,

# reduce 24 omitted

module_eval(<<'.,.,', 'parser.y', 30)
  def _reduce_25(val, _values, result)
     result = val[0] + val[1] 
    result
  end
.,.,

# reduce 26 omitted

module_eval(<<'.,.,', 'parser.y', 33)
  def _reduce_27(val, _values, result)
     result = val[0] + val[1] 
    result
  end
.,.,

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_38(val, _values, result)
     result = '' 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 40)
  def _reduce_39(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 40 omitted

module_eval(<<'.,.,', 'parser.y', 43)
  def _reduce_41(val, _values, result)
     result = val[0] + val[1] 
    result
  end
.,.,

# reduce 42 omitted

# reduce 43 omitted

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_44(val, _values, result)
     result = '!' 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_45(val, _values, result)
     result = "'" 
    result
  end
.,.,

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_50(val, _values, result)
     result = val[0].to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 55)
  def _reduce_51(val, _values, result)
     result = "#{val[0]}#{val[1]}".to_f 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_52(val, _values, result)
     result = "#{val[0]}#{val[1]}".to_f 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 57)
  def _reduce_53(val, _values, result)
     result = "#{val[0]}#{val[1]}#{val[2]}".to_f 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 59)
  def _reduce_54(val, _values, result)
     result = val[0].to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_55(val, _values, result)
     result = "#{val[0]}#{val[1]}".to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_56(val, _values, result)
     result = "-#{val[1]}".to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 62)
  def _reduce_57(val, _values, result)
     result = "-#{val[1]}#{val[2]}".to_i 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_58(val, _values, result)
     result = "#{val[0]}#{val[1]}" 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 66)
  def _reduce_59(val, _values, result)
     result = "#{val[0]}#{val[1]}" 
    result
  end
.,.,

# reduce 60 omitted

module_eval(<<'.,.,', 'parser.y', 69)
  def _reduce_61(val, _values, result)
     result = "#{val[0]}#{val[1]}" 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 71)
  def _reduce_62(val, _values, result)
     result = 'e' 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_63(val, _values, result)
     result = "e-" 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class Parser
    end   # module Object
  end   # module Rison
